### ISSUE TITLE
Load From Files (not just URL)

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#100]
There are a few places where in order to load or open a file (website import image and in web client), you have to specify a URL.  Should be able to do the same from a local file.  See Specification for this enhancement (Load from File Spec.docx):
https://drive.google.com/drive/u/0/folders/0B3UI2GmfMrltVkpzMHJaQU1LNlk

**Comment by astrojonathan** [comment]
FIxed
