### ISSUE TITLE
Instructions on how to start SAMP?

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/wwt-web-client#104]
The following page mentions that there is a SAMP interface to WWT:

http://www.worldwidetelescope.org/Researchers/

Is this available in the web client version of WWT? If so, would it be possible to add instructions on how to start this, and outline which SAMP messages WWT understands?

**Comment by astrojonathan** [comment]
Currently SAMP is only supported on the Windows Client. There is currently significant effort going on in improving the web client, and the infrastructure to support needed to support the visualization of Web SAMP compatible data types means that we will be a step closer to supporting it.

**Comment by doctorspaceman** [comment]
There is an example of using SAMP to connect WWT (Desktop Client) to TOPCAT: 

www.worldwidetelescope.org/Learn/Exploring#UsingVOTables.

As Jonathan said, we are putting in the groundwork to enable SAMP in the webclient as we speak.  If you have anything specific you'd like to see or any tests let us know by responding to this issue.

**Comment by astrojonathan** [comment]
SAMP may be a non starter on web because of Security changes in browsers.
