### ISSUE TITLE
Efficient way to add many annotations in web client

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/wwt-web-client#105]
I am interested in adding e.g. 10,000 markers from a catalog to WWT in the web client. However, if I use `wwt.addAnnotation`, the client becomes extremely slow. Is there a more efficient way to load datasets such as this?

**Comment by astrojonathan** [comment]
The current WebClient is using a HTML5 canvas to render and doing 3d transforms on that many objects is expensive. We are working on a WebGL port of the web client right now, one done you should be able to do over 100k with no issue. The code is working right now and we see huge performance gains and great frame rates, but we are also porting Tour Authoring and layer display as well and will post a updated version of the web client once all of those are build and tested.

**Comment by astrofrog** [comment]
@astrojonathan - just to follow up on this, you mention 3d transforms, so I was wondering whether there is a way to avoid doing 3d transforms and just work with the '2d' sky?

**Comment by astrofrog** [comment]
@astrojonathan - with the WebGL version now available for preview (looks great!) is there an easy way to use the WebGL version instead of the plain HTML5 version? For instance I have an HTML page with:

```
    <title>Simple WWT Web Client</title>
    <script src="http://www.worldwidetelescope.org/scripts/wwtsdk.aspx"></script>
    <script src="http://code.jquery.com/jquery-1.8.3.min.js"></script>
```

How can I change this to use the WebGL version? Does that version have a compatible JS API?

Note that even if the WebGL version can show 100k points with no issue, I think I would need a more efficient way to plot these than one by one. Is there a planned JS API for plotting larger catalogs of points? (without having to save the catalog to disk).

**Comment by astrojonathan** [comment]
The new Data Layers functionality addresses this
