### ISSUE TITLE
Enabling Galactic plane mode from JS API

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/wwt-web-client#106]
I would like the option to enable/disable the 'Galactic plane mode' from the Javascript API, but I could not find anything here:

http://worldwidetelescope.org/Developers/HTML5SDK

Is there no way to do this yet, or is it simply not documented?

**Comment by astrojonathan** [comment]
Try this setting. It was created after the API documentation was last updated.

wwtControl.settings.set_galacticMode(true);

**Comment by astrofrog** [comment]
@astrojonathan - that worked, thanks!
