### ISSUE TITLE
Web Authoring Testing #1

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#109]
These aren't individual issues, but bundled together from a lengthy test of the web client tour authoring.

-   It doesn't keep me logged in.  When I click "Sign In" I get the splash screen at each stage (3 times I think).
-     Can't delete working tour with X
-     Protect against PAGE-BACK killing tour or check about saving state to IndexDB. Recreating the state.
-     Transitions don't work. I can adjust the times (A/Hold/B)
-     Image cross-fader doesn't work (Talked to Ron and he said that it was because of WebGL "setforegroundopacity" in WebGL, check with Jonathan?)
-     Selecting shape (I love the UI) doesn't work
-     Selecting image overlay doesn't work (Ron is passing reference to the local selected file this, but it throws WebGL errors)
-     Master slide doesn't do anything
-     Can't adjust slide time (Ron isn't clear about the where this is controlled)
-     Can't adjust slide time (Ron isn't clear about the how the slide duration is exposed)
-     Can't name slide (right above the time at the bottom)
-     Under Guided Tours tab in Menu
-         Missing "Show Slide Overlay" selection/box
-         Missing "Show Slide Number" selection
-     Selecting/De-selecting layers (e.g., Constellation Lines) doesn't fade

I have made a list of actions I user would use to make a web authored tour. They are listed in the Word Document here: 
[Web Authoring Functionality List.docx](https://github.com/WorldWideTelescope/wwt-web-client/files/402979/Web.Authoring.Functionality.List.docx)

I have also made a video showing this in action (8m) on YouTube here: https://youtu.be/5jFwUdHbaVE

**Comment by thewebkid** [comment]
My estimates + some comments:

- Sign in issue 1h
- Close tour issue 2h
- Recreating Tour from saved state 2-8h 
  (depending on how jonathan stores objects in indededb - he will need to serialize the state into json so I can rematerialize the objects if those objects are present in localStorage)

- Transitions 1-2h (I need some guidance on what to call in the api)
- Need jfay to look at this. I am defn still calling WWTControl.singleton.renderContext.viewCamera.opacity = opacity;
- Selecting shape, image, and set master slide I suggest jfay to investigate
- Adjusting slide time and label (name) will be tricky to implement from a UI standpoint, but I think I can find the api to call. I was more confused about the transition api and the a-time, b-time, etc. 4-6h estimate.
- Show overlay list is maybe 4 h - due to it being a new modal type that persists while you are interacting elsewhere. Could be tricky. Maybe only 1-2h. Also need to verify that the api hooks are there
- Show slide numbers will be likely a 2 hour fix
- Layer manager stuff - that looks like jfay issue unless there is something I need to do on my end...

The UI tour could take 2-4 days to create. (10-20h)

There are things not mentioned like glue to the user community - though the back end is already there. We need forced login dialog, a dialog when tour is uploaded to user community+share tour now, creating two UI feature tour entry points, wire up text and disable ranges, and unforeseen bugs, additional UI support Jonathan needs. We will also need to put the working code back to _not_ default to edit mode so we can have normal playback->esc key->edit tour behavior. This is at least another 20h of work.

I hope it goes faster :)

**Comment by doctorspaceman** [comment]
Critical Web Authoring Issues

-     Can't delete working tour with X.  Keeps re-showing the same tour you tried to delete.
-     Protect against PAGE-BACK killing tour or check about saving state to IndexDB. Recreating the state.
-     Image cross-fader doesn't work (WebGL "setforegroundopacity" in WebGL, check with Jonathan?)
-     Selecting shape (I love the UI) doesn't work
-     Selecting image overlay doesn't work (Ron is passing reference to the local selected file this, but it throws WebGL errors)
-     Master slide doesn't do anything
-     Can't name slide (right above the time at the bottom)
-     Under Guided Tours
-         Missing "Show Slide Overlay" selection/box
-         Missing "Show Slide Number" selection
-     Selecting/De-selecting layers doesn't fade
-     What happens if I start editing on-line and then loose connection?  And then shut things down?
-     Slide Start-End Ears should always show a state (beginning or end).  Not sure of the logic in the desktop client but it should be included here.
-     Can't seem to set end camera position.
-     Slide Duration works (both with up/down arrows and direct entry)!  Great!!!
-     The "Run Time" (under the Play/Pause button) doesn't change from changing the slide durations.
-     Transitions (except for moveto "-->") aren't wired up.
-     Adding Audio to slide isn't wired up.

Non-Critical Issues
-     When you create a tour and get a dialog box can the username and email be extracted from the LiveID login?

**Comment by doctorspaceman** [comment]
**Fonts**

    Fonts don't include the entire font set of the desktop client.  If at all possible, can you get the Segoe UI font family?  That is the official font for the website and a very readable font for tours.  Also if you don't have all the same fonts what happens when you try to play/open a tour created on the desktop client with a font that doesn't exist in the web client?
    I can make the text box, but some issues:
        If I set color properties (text of background) they are shown in the edit window but not the saved text.
        I should be able to double-click to open the text editor box.
        I can right-click on the text box to get the context menu, but it also brings up the finder scope. 
        When I do right-click on text box (which does show any color properties I set - but weren't shown) and select edit I get the text editor and adjust properties but the SAVE button isn't active and all I can do is to click X to close the window. When I do close the window, the box is super small (see attached JPEG). When I move the main view that super small text box goes away and I think the object is really gone.  After this when i try to add another text box the editor comes up and I can interact with it but I can't save it.

**Shapes**

    I see the Shapes work now.  It has the same issue that right-clicking pulls up the finder scope.  The color property and handles seem to be working but opacity isn't shown in the UI and not adjustable.
    Mapping issues:
        Selecting Open Rectangle brings up Star.
        Selecting Line brings up Arrow
        Selecting Arrow brings up Line
        Selecting Star Brings up Open Rectangle

**Picture Overlay gives selector but doesn't show image.**

![web-client-text-box](https://cloud.githubusercontent.com/assets/9676722/17898886/040c1d76-691f-11e6-8ed8-d542a1b31e46.jpg)

**Comment by thewebkid** [comment]
Using Segoe UI is tricky. We can add it to the dropdown, but it will not render on a non-windows device so I recommend against it. There is no way for Jonathan's text object to accept a failover font the way we can in css. 
http://stackoverflow.com/questions/3911816/using-font-face-for-segoe-ui-font

**Comment by doctorspaceman** [comment]
From Testing 8/30/16

Test Tour: Guided Tours/Nebula/Seeing the Invisible

 

Browser Variations

    Edge and IE11 can't save local file
    Firefox takes a lot of CPU compared to Edge, IE11 and Chrome
    Slide 3-8 of Test Tour shows an overlay IR image. In Chrome, Edge and Firefox the IR foreground image is black.  In the Desktop it is correct and in IE11 it is missing completely.
    Right clicking on an overlay object to get its context menu brings up the finder scope as well for IE11, Edge & Firefox.
    MINOR: In IE11, the "Do not show me this dialog box again" is to the right of "Show the web client as landing page."  On other browsers it is below.
    IE11 and Edge when you create a new Tour it looks like there is no first slide shown (but I think there is but it is not shown).  So when you click on the "add new slide" thumbnail, you get the hidden slide 1 revealed plus slide 2.  On Firefox and Chrome you get a slide 1 when you create the tour.

 

General Issues (HIGH PRIORITY)

    Until we have the 3D Solar System parts in WebGL (planets, asteroids) we should take out the existing 3d Solar System items in the layer manager. VERY IMPORTANT!
    Until saving tours in progress and re-attaching is working we need to put a warning about asking a confirmation before navigating away from page so people don't loose work.  VERY IMPORTANT!
    When Creating New Tour, Tour Properties section on right (overlays, tour properties box, audio). VERY IMPORTANT!
    On Chrome. When I Create a new tour and on slide 1 right click and set start camera position.  Zoom in. and Set end Camera position I should have a 10 second zoom in. I can't get this simple behavior to work (making slides with begin/end and playing it). 
    Playing short tour (2 slides, 10 seconds each).  It never ends.
    Yellow highlighted box doesn't track active slide
    Clicking on Start/End slide ears doesn't keep them yellow after clicking (as it does in the desktop client).
    Run Time is same for all browsers but different than the Desktop Client.  Test tour is 8:41 in web and 10:47 in Desktop client.
    If I have an overlay object selected and delete the tour the tour goes away but object stays. It should go away with the tour.

 

General Issues (LOW PRIORITY)

    Status bar for download from cloud to browser.
    Objects in the FOV at bottom are updated as tour plays.  It should be turned off as it kills performance.
    Under Guided Tours, there should be a menu in the pulldown to "Save Tour As…" which brings up a dialog box to save to Community or local file.
    Open Tour should have a "Choose file in community" which browses your community (VERY LOW PRIORITY)
    Slide names (above time) aren't implemented.
    Serializing tours and saving as much as we can (and having some way to show that an unsaved tour in progress) so it could be re-attached when you start to edit a tour.

 

Ron:

    When browsing and selecting a tour it should start in play mode.  The Guided Tour/Edit Tour pull-down should enable editing
    Make sure when you create a tour it starts in edit mode.

**Comment by doctorspaceman** [comment]
Captured results of extensive testing.  This document has all issues (including those above) that are outstanding.

**Comment by doctorspaceman** [comment]
Here is the tour that does play in the web but does not in the desktop.  I think the issue is that it has an image overlay.
[WorksInWebNotInDesktop-HasImage.zip](https://github.com/WorldWideTelescope/wwt-web-client/files/449612/WorksInWebNotInDesktop-HasImage.zip)

**Comment by doctorspaceman** [comment]
New Testing document with revisions from 9/1/2016

[Web Authoring 4 - 8-31-2016-REVISED-9-1.zip](https://github.com/WorldWideTelescope/wwt-web-client/files/449936/Web.Authoring.4.-.8-31-2016-REVISED-9-1.zip)

**Comment by doctorspaceman** [comment]
New Testing with revisions 9/2/16

[Web Authoring 4 - 8-31-2016-REVISED-9-2.zip](https://github.com/WorldWideTelescope/wwt-web-client/files/451878/Web.Authoring.4.-.8-31-2016-REVISED-9-2.zip)

**Comment by doctorspaceman** [comment]
I have separated out all issues individually into issues and am closing this catch all one.  Note the new issues are put into categories Low, Medium, High.

**Comment by thewebkid** [comment]
Ok, well all my cycles tonight are chewed up, but I did accept 3 pull
requests to the web site (one guy). I asked if he wanted to help with the
web client documentation (versioning) as we need at the very least a
revision to reflect the new sdk location, version numbers, and any new api
enhancements (which I can think of a few).

We can focus on that after we release obviously.
