### ISSUE TITLE
While editing tour, navigating to another tab and then back to tour, slides are not shown

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#111]
Steps to repro:

1. Start editing a tour and make some slides.
2. Navigate to Explore tab
3. Go back to the tab of the tour you were creating

The slides you created are not shown.  When you click "Add New Slide" they all appear (with the new slide at the end).

**Comment by doctorspaceman** [comment]
Ron, model syncing.

**Comment by thewebkid** [comment]
Done. Staged. Pushed.
