### ISSUE TITLE
Play/pause state

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#112]
When playing a tour with the play button the button changes to Pause button, but stays that was at tour end.  It should go back to Play when it gets to the end.

**Comment by doctorspaceman** [comment]
I think this is related to the pause/play state, but when I let the tour play to the end and it is stopped on with the Pause button showing but it is really at the end and stopped.  In this state I am allowed to enter text but it doesn’t show up until I hit the Pause button.

**Comment by thewebkid** [comment]
I need to add a dialog when the tour ends and trap this. New changes to tour state though. Hopefully I can bang this out tomorrow...

**Comment by thewebkid** [comment]
actually, let's close this issue - just verified all my autohide work fixed this. We need a new issue at lower priority for the tour dialog at the end of playing.
