### ISSUE TITLE
Can't add audio to "Voiceover" (it ends up under music)

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#121]
Adding Audio to Voiceover puts it under Music.  No way to add Voiceover.  Good news is that I’ve tested audio mixing (Master + per-slide audio) and that works!

**Comment by doctorspaceman** [comment]
Ron can do this.

**Comment by thewebkid** [comment]
I did it. Staged/pushed. See my fun email
