### ISSUE TITLE
In Earth/Planet modes layer manager is too long

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#126]
Under Earth and Planet modes, the layer manager is too long and pushes the context menu at the bottom off the screen.  See attached screenshot.

![cut-off context menu](https://cloud.githubusercontent.com/assets/9676722/18356908/65915826-75b4-11e6-8b7e-59a54982cc12.jpg)

**Comment by thewebkid** [comment]
removed thumbnails from context panel. Shortening height is on purpose - we need to implement new skyball area for feature parity. Skyball was hidden due to constraints at the time. Consider updating in future.
