### ISSUE TITLE
Non-numbers in slide duration field

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#130]
Shouldn't allow non-numbers in the time field for the slides. (moved this to MEDIUM PRIOITY since after entering non-number it is removed and doesn’t cause an issue.

**Comment by doctorspaceman** [comment]
(moved this to MEDIUM PRIOITY since after entering non-number it is removed and doesn’t cause an issue).

**Comment by doctorspaceman** [comment]
Related issue, you can't edit the fractional second field.  Only the second and minute field.

**Comment by thewebkid** [comment]
This can now be edited. Fractions and the text validator works and will not allow non-numeric vals to persist
