### ISSUE TITLE
Saving Under Mac/Firefox

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#139]
* The output name doesn't have an extension.
* Writing output file name has a problem and the dialog box in Mac OSX Firefox is short and you can't tell where it is writing and since you can't search by extension finding it is a problem.
* Can we just use the output name "TOUR_NAME.wtt" by default?  See issue #138

**Comment by doctorspaceman** [comment]
Ron or Jonathan could look into this.

**Comment by doctorspaceman** [comment]
I've confirmed that this only happens with Firefox under Mac. Under windows it saves with the proper extension.

**Comment by thewebkid** [comment]
Ok, I have checked in code that works on windows edge + chrome. Can either
of you confirm by going to staging and testing?

**Comment by doctorspaceman** [comment]
I've confirmed this works as advertised.  Great job!  Closing this.
