### ISSUE TITLE
Can't load tour from file on Mac/Firefox

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#140]
Trying to load a tour file (created in Mac-Firefox) gives an error: "javascript:$('#addFile').click().  Note, this error shows up in a new page which looses anything before.  It also comes up when I click "Local File" when the dialog box comes up.

**Comment by doctorspaceman** [comment]
Ron can fix this.

**Comment by thewebkid** [comment]
Ok, I have checked in/staged code I believe fixes this, but can't test. Please verify.

**Comment by doctorspaceman** [comment]
I've tested and still doesn't work.  Nothing seems to be have changed.

**Comment by astrojonathan** [comment]
I am able to create a tour in Mac Firefox, then reload it from the downloads directory.

Did you do a hard-refresh on your cache to get the new Js files?

**Comment by doctorspaceman** [comment]
That was the problem!  I've confirmed it is fixed.  Closing.
