### ISSUE TITLE
Mac/Safari hangs when loading tour from file

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#142]
Mac/Safari hangs when trying to open tour created from file.

**Comment by doctorspaceman** [comment]
Ron can look at this.

**Comment by thewebkid** [comment]
added a very primitive alert when user enters edit mode in safari.

**Comment by doctorspaceman** [comment]
Reopening this.  This message comes up on Mac:Chome/Firefox and Windows:Edge/IE11.  Also problem that it does up whenever you navigate to the tour (if you have ignored the message).  If they ignore it you should not bring it up again.  Same as #143.

**Comment by doctorspaceman** [comment]
The message is working fine now.  Closing.
