### ISSUE TITLE
Fade out chrome when playing tour 

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#143]
This behavior should be like the windows client.  Would be nice to go full screen.

Ron will  work on this

**Comment by Coder206** [comment]
@doctorspaceman Is something like this what you had in mind? (Link: http://html5-demos.appspot.com/static/fullscreen.html)

**Comment by thewebkid** [comment]
fixed/pushed/staged

**Comment by doctorspaceman** [comment]
This does fade out but doesn't fade-in when the mouse goes over menus.   Hitting escape stops tour with no menus to do anything.

**Comment by doctorspaceman** [comment]
Can't repro the hiding but never coming back so closing this issue.
