### ISSUE TITLE
Solar system clipping plane issue with large orbits

### ISSUE THREAD

**Issue by AstroRob** [WorldWideTelescope/wwt-web-client#149]
When adding some outer bodies past Neptune with large orbits there are still some clipping plane issues. This had been partly resolved some months ago, but a new family of objects are now exhibiting similar behaviors.

**Comment by astrojonathan** [comment]
I will take a look at it. What in the world do you have so far out there? We might have to redefine what we call the solar system! I can try to allow for orbits going further but in managing the z-buffer, we will lose some resolution when we trade resolution for greater distances of what we consider inside the Solar System. I can make this a bit more dynamic but it will take a bit more code.

I will post you an update after I dig in a little more.

**Comment by astrojonathan** [comment]
Was able to increase the depth buffer distance for far out objects and it fixes the problem!
I am checking in the update in a few minutes and will send you a link to a private build.
