### ISSUE TITLE
Webclient tour authoring not active/available

### ISSUE THREAD

**Issue by erinjohn** [WorldWideTelescope/wwt-web-client#150]
Instructions given on the[ AAS](url) and WWT websites both indicate that tour authoring in the webclient is "active".  This is not the case.  Webclient is not linked to the version where web-based tour authoring is available.  The only version where webclient tour authoring is possible appears to still be in "staging" -  following this link: http://wwtstaging.azurewebsites.net/webclient/

Following the links that advertise the AAS competition and encourage folks to enter takes users to a the version of the webclient where they are not yet able to create tours: 
<img width="828" alt="screenshot 2016-11-30 09 59 15" src="https://cloud.githubusercontent.com/assets/12798707/20757397/1674d116-b6e4-11e6-9407-546ec8a84be4.png">

**Comment by pkgw** [comment]
Nearly four years later ... this in fact has been fixed!
