### ISSUE TITLE
Bug in goToRaDecZoom with instant panning and galactic mode

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/wwt-web-client#160]
The following series of screenshots demonstrates the issues. I start off with:

```
wwt = wwtlib.WWTControl.initControl("WWTCanvas");
```
![screen shot 2017-07-27 at 11 38 34](https://user-images.githubusercontent.com/314716/28666693-64cd0098-72c0-11e7-8a36-dd08e5f83227.png)

I then set the mode to galactic and pan instantly to a location:

```
wwt.settings.set_galacticMode(true)
wwt.gotoRaDecZoom(274.4287842172836, -13.813520150682765, 0.1, true) 
```

![screen shot 2017-07-27 at 11 38 50](https://user-images.githubusercontent.com/314716/28666713-7a64c184-72c0-11e7-8b5a-6520929fc586.png)

However, the location shown is incorrect. If I then change to non-instant panning, it then pans to the correct location

```
wwt.gotoRaDecZoom(274.4287842172836, -13.813520150682765, 0.1, false) 
```

![screen shot 2017-07-27 at 11 39 17](https://user-images.githubusercontent.com/314716/28666750-9c626fa2-72c0-11e7-892a-83c673fe1af6.png)

**Comment by astrojonathan** [comment]
I would suggest using the following line of code to get a WWT object. Using the initialize and using the variable wwt is a bad idea, it will cause some errors and potentially change the state of the client.

Try this instead
mywwt = wwtlib.WWTControl.singleton

I was able to repro this without the additional console errors and will look into it. The declination did not go to the correct location when I did an instant jump.
