### ISSUE TITLE
Add Open For Edit Checkbox in Tour Open Dialog

### ISSUE THREAD

**Issue by philrosenfield** [WorldWideTelescope/wwt-web-client#164]
There are no options to edit an existing tour. So if you don't finish a webgl tour in one sitting, you have to start over.

**Comment by astrojonathan** [comment]
The Edit is in the tour menu, same as the Windows Client.

Open The tour. Hit escape or stop playback. 

Click Tour...Edit.. in the menu options.

Maybe we should have an Open for Edit Checkbox in the Open dialog to make in more deliberate.

Changing the title to reflect this.

**Comment by thewebkid** [comment]
Fix pushed to master and staged
