### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/wwt-web-client#172]
On the following page:

https://worldwidetelescope.gitbooks.io/worldwide-telescope-web-control-script-reference/content/webcontrolobjects.html#wwtcontrol-loadtour-method

In the following text:

*Tours can be stand-alone, or part of collections. For more information on tours refer to the WorldWide Telescope User Guide, and also to the WorldWide Telescope Data Files Reference document.*

the link 'WorldWide Telescope Data Files Reference' is broken.

**Comment by philrosenfield** [comment]
Thanks. I’ll get to this next week, the link should be:
https://www.gitbook.com/book/worldwidetelescope/worldwide-telescope-data-files-reference

**Comment by pkgw** [comment]
This was fixed at some point.
