### ISSUE TITLE
Polygon fill does not work for polygons in certain directions

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/wwt-web-client#181]
Using the staged WebGL SDK, there is an issue with the filling of polygons when the vertices are in one direction versus the other:

```js
poly1 = wwt.createPolygon()
poly1.addPoint(0,0)
poly1.addPoint(0,1)
poly1.addPoint(1,0)
poly1.set_fill(true)
wwt.addAnnotation(poly1)

poly2 = wwt.createPolygon()
poly2.addPoint(2,0)
poly2.addPoint(3,0)
poly2.addPoint(2,1)
poly2.set_fill(true)
wwt.addAnnotation(poly2)
```

The result is:

<img width="195" alt="screen shot 2018-08-15 at 17 31 02" src="https://user-images.githubusercontent.com/314716/44160123-51fd2400-a0b1-11e8-9545-1bf264947026.png">

With poly2 on the left, and poly1 on the right.

**Comment by astrojonathan** [comment]
Polygons have a specific counter-clockwise winding direction. The fill faces the normal of the triangles generated by tessellation. This behaviour is by design.
