### ISSUE TITLE
Rendering issues for single-planet mode

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/wwt-web-client#187]
When doing:

```js
wwt.setBackgroundImageByName('Earth');
```

there are rendering issues:

<img width="724" alt="screen shot 2018-12-19 at 00 48 02" src="https://user-images.githubusercontent.com/314716/50191879-c11caa80-0327-11e9-82dd-458cb71b8d00.png">

This is also an issue e.g. for the moon:

<img width="468" alt="screen shot 2018-12-19 at 00 48 43" src="https://user-images.githubusercontent.com/314716/50191900-e14c6980-0327-11e9-8666-57fd80f89361.png">

@astrojonathan - any idea what could be causing this? I'm using Chrome on MacOS X

**Comment by pkgw** [comment]
Seeing this too on Linux.

**Comment by astrojonathan** [comment]
This is a result of having two incompatible maps in foreground and background. If you have 3d Geometry on both, then the one that is the highest covers the one with lower elevation.

**Comment by astrojonathan** [comment]
The only way to see two full planet layers is for them to use the same projection, or to have elevation turned off.

**Comment by astrofrog** [comment]
@astrojonathan - ah I see, this is indeed fixed by setting:

```
wwt.setForegroundImageByName('Earth');
```

Just to check, are there any maps of earth that aren't nighttime ones?

**Comment by astrojonathan** [comment]
We need to make sure just the background is set for Single Planet mode. Not sure why FG was set to begin with, do you have a notebook I could repro this on?

**Comment by astrojonathan** [comment]
You can look at the list of image sets from the downloaded XML in the client, or just use the Web or Desktop UI and select Planet, Earth, etc. and then look at the dropdown for the list of available sets, then pass that name to the setByName functions..
Bing Maps Ariel
Bing Maps Hybrid
Bing Maps Streets

These are some of the super details depp tile image sets for Earth w/DEM.

**Comment by astrofrog** [comment]
You can reproduce the issue we had with:

```html

<!DOCTYPE html >
<html style="height: 100%; padding: 0px; margin: 0px; background-color: #000000;">
  <head>

    <meta charset="utf-8" http-equiv="X-UA-Compatible" content="chrome=1, IE=edge"/>

    <title>Simple WWT Web Client</title>
    <script src="https://WorldWideTelescope.github.io/pywwt/wwtsdk.js"></script>
    <script src="https://code.jquery.com/jquery-1.8.3.min.js"></script>
    <script src="wwt_json_api.js"></script>

    <!-- The following is to avoid scrollbars -->
    <style type="text/css">
      body {overflow:hidden;}
    </style>

    <script>
        $(document).ready(sizeContent);
        $(window).resize(sizeContent);
        function sizeContent() {
        var newHeight = ($("html").height()) + "px";
        var newWidth = ($("html").width()) + "px";
        $("#WWTCanvas").css("height", newHeight);
        $("#WWTCanvas").css("width", newWidth);
        }
    </script>

    <script>

      var wwt;
      var wwt_ready = 0;

      function initialize() {
        // The true enables WebGL
        wwt = wwtlib.WWTControl.initControlParam("WWTCanvas", true);
        wwt.add_ready(wwtReady);
      }

      function wwtReady() {

        // We set the initial values of the settings here, because there is no
        // easy way to find out when the Jupyter widget has finished loading
        // and WWT is ready from there.

        wwt.loadImageCollection('https://WorldWideTelescope.github.io/pywwt/surveys.xml')
        wwt.setForegroundImageByName('Digitized Sky Survey (Color)')
        wwt.setBackgroundImageByName('Hydrogen Alpha Full Sky Map')
        wwt.setForegroundOpacity(80.0)

        wwt.setBackgroundImageByName('Earth')

      }

    </script>
  </head>

  <body onload="initialize()" style="margin: 0; padding: 0">
      <div id="WWTCanvas" style="width: 100; height: 100; border-style: none; border-width: 0px;"></div>
    </div>

  </body>
</html>
```

Basically in some cases we set the foreground and background while in sky mode, and then later switch to Earth. The only way to then avoid the artifacts is to do:

```js
        wwt.setBackgroundImageByName('Earth')
        wwt.setForegroundImageByName('Earth')
```

**Comment by astrojonathan** [comment]
I think we will have to clear the Foreground image or set it to match the background. I will check to see if the Web Client behaves the same as the Windows client, but if you set both foreground and background to the same imageset the Desktop version will clear the FG imageset to empty to avoid wasting time drawing the same thing twice.

**Comment by astrojonathan** [comment]
Also looking some more it is clear that the DSS dataset is still showing up. Maybe we should clear the foreground dataset when it does not match the background in content type. IE can't mix sky with planet maps.

**Comment by astrofrog** [comment]
> Maybe we should clear the foreground dataset when it does not match the background in content type

That sounds reasonable to me!

**Comment by astrojonathan** [comment]
I checked the Windows Client It does not remove redundant foreground imagesets.

**Comment by astrojonathan** [comment]
I would suggest you use 
wwtlib.WWTControl.singleton.renderContext.set_foregroundImageset(null);

This will reset the FG imageset so you won't have a conflict.
