### ISSUE TITLE
Web client iPad functionality poor

### ISSUE THREAD

**Issue by willum070** [WorldWideTelescope/wwt-web-client#19]
menus doesn't work (they stack on top of each other) - layer manager doesn't close - perf is poor in both Ipad chrome and safari

**Comment by egcarter** [comment]
iPad functionality and performance is poor.

**Comment by kfogel** [comment]
Replaced "Prio2" label with "Soon after Jan 2016 AAS" milestone.  If that's the wrong milestone to mean what "Prio2" meant, please set to the appropriate the milestone (the "Prio" labels will be going away, as per phone call today with @patudom and @doctorspaceman).

**Comment by thewebkid** [comment]
This is a difficult one for me to track down. The only thing I have close to an ipad is an android tablet, a surface, and an emulator tool in the browser. To properly address this, I would need to have a list of specifics, and then a way to reproduce them with an ipad. I think this will end up being lower pri.

**Comment by astrojonathan** [comment]
Web GL has made a huge difference. IPad performance is not much better
