### ISSUE TITLE
Weird visual effects when switching from 3D to Sky view

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/wwt-web-client#199]
When switching from 3D to Sky view, I get weird visual 'Star Trek'-style effects. Sometimes this happens straight away, and sometimes after the first click in the window after switching view:

![startrek](https://user-images.githubusercontent.com/314716/51266492-55c00a00-19b3-11e9-8f3f-e75cf7d7e9c2.gif)

**Comment by pkgw** [comment]
I believe this is fixed!
