### ISSUE TITLE
Saturn's rings are missing

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/wwt-web-client#200]
In the 3D solar system mode, Saturn is missing its rings:

<img width="614" alt="screenshot 2019-01-16 at 17 42 57" src="https://user-images.githubusercontent.com/314716/51267702-42626e00-19b6-11e9-8fef-ea513e5baa7c.png">

**Comment by astrojonathan** [comment]
This appears to the the planet mode, not 3d Solar System mode. Check the code you are using to activate this.

**Comment by astrofrog** [comment]
@astrojonathan - sorry yes I meant to say planet mode. Can I reopen this issue, or is this not fixable?
