### ISSUE TITLE
For FITS images, values scaled to 0 should not be transparent

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/wwt-web-client#211]
Currently, when passing a FITS image to WWT, values in the array that are scaled to an integer value of zero should be shown as black not as transparent. Here's an example of a stellar images where many of the background values are scaled to an integer value of zero:

![screenshot 2019-03-08 at 17 53 33](https://user-images.githubusercontent.com/314716/54046057-30899400-41cb-11e9-991b-a6dbb8f58c30.png)

**Comment by astrojonathan** [comment]
There is a property called "TransparentBlack" on the FitsImage in the layer. Set it to false to turn this off.

**Comment by astrofrog** [comment]
@astrojonathan - thanks!
