### ISSUE TITLE
Weaknesses in RA/Dec parsing in the search ribbon

### ISSUE THREAD

**Issue by pkgw** [WorldWideTelescope/wwt-web-client#212]
A NASA user reported two weaknesses in the ways that the RA and Dec entries work in the Search ribbon. Both work in the Windows client.

1. Often people will type sexagesimal coordinates with spaces in between the numbers instead of colons. E.g., `12 34 56.7` instead of `12:34:56.7`. It seems that everything after the first space will be ignored: the webclient will take the user to `12:00:00` instead.

2. Negative declinations are mis-parsed. The negative sign has to be handled specially and applied to all elements of the coordinate. Currently, `-00:01:30` gets parsed into `+00:01:30`, and `-01:00:30` gets parsed into `-00:59:30`. Because of the possibility of a leading `-00`, you can't just look at the sign of the resulting `atoi(degrees)` — you have to specifically look for a minus sign and apply it at the end of the computation.

**Comment by thewebkid** [comment]
Pushed fix to my working branch. Staged. Please verify.

**Comment by astrojonathan** [comment]
The negative declination is still not fixed. I could use 12 23 45 for RA and that was correct, but dec of -12.5 when to -13:30

**Comment by thewebkid** [comment]
In this example, I am calling wwtlib.Place.create('tmp', -185.8916, -12.5,...) correctly which you can see in the debugger on the right side scope panel 

But the dec still goes to -13:30 when I call gotoTarget

ideas?

![image](https://user-images.githubusercontent.com/303043/54441872-d3c23800-46fa-11e9-94de-184a7020201d.png)

**Comment by astrojonathan** [comment]
Sorry. I did not make it clear, you have a display problem. I e-mail thread
I was pointing our was showing that your rounding code is jumping too much.
Just drag the mouse slowly down and watch the declination, when you get
above .5 it jumps to -1.5

**Comment by thewebkid** [comment]
I found it in int2. Staged temp fix so you can verify. Will check in with my observing location commit later.

**Comment by astrojonathan** [comment]
Still issues

I enter 0,12.5 I get 0, 13:30:00

I enter Blank, 12.5 I get black screen and permanent crash.

Need to make sure we don't crash with various input.

**Comment by thewebkid** [comment]
fix pushed and staged
