### ISSUE TITLE
Continuous integration broken

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/wwt-web-client#215]
The CI build is now erroring with:

```
HTML5SDK\wwtlib\WWTControl.cs(738,24): Error CS0120: An object reference is required for the non-static field, method, or property 'MercatorTile.GetSurfacePointAltitude(double, double, bool)'
HTML5SDK\wwtlib\WWTControl.cs(741,22): Error CS0103: The name 'currentImageSetfield' does not exist in the current context
HTML5SDK\wwtlib\WWTControl.cs(743,24): Error CS0103: The name 'TargetAltitude' does not exist in the current context
HTML5SDK\wwtlib\WWTControl.cs(745,22): Error CS0103: The name 'currentImageSetfield' does not exist in the current context
HTML5SDK\wwtlib\WWTControl.cs(747,24): Error CS0103: The name 'GetAltitudeForLatLong' does not exist in the current context
Process 'msbuild.exe' exited with code '1'.
```

Here is the link to the log:

https://dev.azure.com/thomasrobitaille/wwt-web-client/_build/results?buildId=267

@thewebkid - it looks like this has started happening following the latest changes you've made (the last successful run was 6690d86d1c588d8d89182d5c1cd1ebcb2618abb9). Is it an easy fix?

**Comment by astrofrog** [comment]
I think the problematic commit is https://github.com/WorldWideTelescope/wwt-web-client/commit/1f7b70d6b518ea583553e86af3a3d0e759fad748#diff-e175ed9960e517302b3a0c6f77569ca1

**Comment by thewebkid** [comment]
I am currently travelling and can't test, but I pushed bits that should resolve this. The getEarthAltitude was a stub I ended up implementing in another branch. Sorry for messing up the build. Can you verify this fixes and then close the bug if it does.

605663d22742399606b9ba25e5431bdb8c837cb9

**Comment by astrofrog** [comment]
@thewebkid - yes it's all passing now, thanks! (https://dev.azure.com/thomasrobitaille/wwt-web-client/_build/results?buildId=272)
