### ISSUE TITLE
Error when setting foreground to Black Sky Background

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/wwt-web-client#218]
The following works but still raises an error:

```
wwt.setForegroundImageByName('Black Sky Background')
undefined
black/:1 GET http://black/ net::ERR_NAME_NOT_RESOLVED
```

No such error is raised if setting the background.

**Comment by astrojonathan** [comment]
This is a "Virtual" imageset. It allows you to have *NO* background image drawn at all. Since Foreground Can be null, you never should use this on foreground, just use null.
