### ISSUE TITLE
64-bit float FITS images do not load any data

### ISSUE THREAD

**Issue by pkgw** [WorldWideTelescope/wwt-web-client#220]
The diagnosis is easy: the loading code [is just commented out](https://github.com/WorldWideTelescope/wwt-web-client/blob/master/HTML5SDK/wwtlib/Layers/FitsImage.cs#L652). Not obvious to me why that's the case.

**Comment by astrojonathan** [comment]
Ill Check it out. Might have been because of a platform issue, but it just might have been not having same to verify with after the port.

**Comment by pkgw** [comment]
This was fixed by @jsub1!
