### ISSUE TITLE
Issues with setting custom image collection URL

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/wwt-web-client#226]
I'm trying to set a custom image collection with ``loadImageCollection`` - unfortunately it's not currently possible to set image collections that live outside the WWT domain, because it looks like at some point when this is called, ``getProxiedUrl`` is called, which I think ultimately only allows WWT URLs to be used. Is there any way to allow arbitrary URLs for image collections?

**Comment by kmi17** [comment]
@astrofrog I am having the same issue. Do you get "Unable to connect to the remote server" response?

**Comment by pkgw** [comment]
@kmi17 In the sample code you emailed, what is the value of the `currentUrl` variable before the call to `wwt.loadImageCollection()`?

As another thing, you are using an old link to the SDK. You should use:

http://www.worldwidetelescope.org/webclient/sdk/wwtsdk.js

**Comment by thewebkid** [comment]
Get proxiedUrl was developed for CORS issues so it ONLY handles external urls. The way you can test to see if your collection url is valid is to use http://worldwidetelescope.org/webclient/?debug=1&wtml=**http://thewebkid.com/hubble.wtml**

Replace the bold text with your image collection url. Can you send me the urls you are trying to load? I can test in standalone mode.

**Comment by kmi17** [comment]
My wtml file is currently hosted in my local machine. I was not sure if
loadImageCollection requires the file to be hosted in a web server or not.

I should be able to host in a web server and test it out. If it doesn't
work then I can send you the URL.

**Comment by astrojonathan** [comment]
Yes. the proxy can't see anything that is not on the public internet.

**Comment by thewebkid** [comment]
You can also use the web client to open a local file to ensure the file is valid and readable by wwt. in worldwidetelescope.org/webclient choose Explore->open->collection, then click choose local file.

**Comment by kmi17** [comment]
Thank you all for helping me out. After I uploaded the file into a web server, the proxy does not complain anymore. Here is the link: https://scitest12.pha.jhu.edu/cellview/Cellview.wtml

**Comment by pkgw** [comment]
@kmi17 Glad to hear it!

@astrofrog I am pretty sure that the issue you initially reported remains, however. The `GetProxiedUrl` function should work with URLs outside of the wwt.o domain, though ([source](https://github.com/WorldWideTelescope/wwt-web-client/blob/master/HTML5SDK/wwtlib/Util.cs#L143)). Is your URL an HTTPS one, or does it get redirected to HTTPS? Usually when the proxy fails for me, I find that that's the issue — the underlying URL-getting service ([source](https://github.com/WorldWideTelescope/wwt-website/blob/master/WWTMVC5/WWTWeb/WebServiceProxy.aspx)) doesn't support SSL. Note that this particular issue is part of the story with WWT's HTTPS support, but orthogonal to a lot of the other issues — we could change the proxy function (as @thewebkid has been looking at) without taking on the HTTPS-ification of the wwt.o frontend. If we were to do that, we could proxy HTTPS only in a way that "loses" the HTTPS security, but it would still allow us to access resources that are currently inaccessible.

**Comment by pkgw** [comment]
Assuming fixed with engine HTTPS revamp. @astrofrog please reopen if needed.
