### ISSUE TITLE
Finder scope won't close

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-web-client#234]
When you bring up the Finder Scope in the web client, clicking on "x" doesn't make it go away.  It persists after changing to different views (like Panorama or Solar System).  The only way we can close the finder scope is to refresh the web client.

**Comment by pkgw** [comment]
FWIW, sometimes I see this problem, and other times it seems fine — it's not obvious to me what might be driving that.

**Comment by thewebkid** [comment]
Fix staged. Please test and confirm the issue is solved.

http://wwtstaging.azurewebsites.net/webclient

**Comment by patudom** [comment]
Now working correctly on my Mac & PC, both in Chrome.  Thank you, Ron!

**Comment by pkgw** [comment]
Woo!
