### ISSUE TITLE
Web Client: J2000 coordinates

### ISSUE THREAD

**Issue by willum070** [WorldWideTelescope/wwt-web-client#27]
Search/Simbad  VO Table Cone search. We should do one of the following: 1. wire this up if easy. 2. doc this as a scenario for future devs. 3. remove it. Also Search/Simbad and VO Table Cone Search don't do anything.

**Comment by kfogel** [comment]
Replaced "Prio2" label with "Soon after Jan 2016 AAS" milestone.  If that's the wrong milestone to mean what "Prio2" meant, please set to the appropriate the milestone (the "Prio" labels will be going away, as per phone call today with @patudom and @doctorspaceman).

**Comment by doctorspaceman** [comment]
The VO cone and SIMBAD search has been removed from the HTML5 webclient.  Closing this.
