### ISSUE TITLE
OpenStreetMap appears twice under collections

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/wwt-web-client#275]
To reproduce:

* Go to http://www.worldwidetelescope.org/webclient/
* In the top bar, click on **Earth**

OpenStreetMaps appears twice in the list of collections:

![osm](https://user-images.githubusercontent.com/314716/77908459-6e98a080-7283-11ea-93ed-a44f5bdacfcc.png)

It might also make sense to use a different icon for OpenStreetMaps compared to Blue Marble.

**Comment by astrojonathan** [comment]
I agree Thumbnails could be different if we had them.
The first first Open Street Map is streets, the second one is BIKE MAPS. If you hover over the thumbnails it will show you the full text. Maybe we should make a Bike Icon over the thumbnail?

**Comment by pkgw** [comment]
In #298 I'm proposing a change to ellipsize the label text in thumbnails with overlong labels. I'm liking how it's looking, and in this case the second "Open Street Maps" thumbnail would acquire an ellipsis indicating that there's more to the name to be seen on mouse-over.
