### ISSUE TITLE
Planet size slider bug

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-web-client#285]
Planet size slider does not work anymore if you switch away from Solar System mode and come back to it.

Steps to reproduce:
1. Go into Solar System view. Planet size slider works fine.
2. Switch to a different view - Sky, Planet, whatever.
3. Switch back to Solar System view. Planet size slider is now locked in the middle position and can't be moved.

**Comment by pkgw** [comment]
Just to make sure, you're confident that this used to work, correct?

**Comment by patudom** [comment]
@pkgw - sorry, no, the "anymore" is in reference to moving away from solar system view and returning, not that there was a recent update that broke this.

I don't recall this specific issue happening in the past, but it's very likely that I never went through the series of steps that triggered it. When I posted the issue, my assumption was that this was always broken and no one noticed or reported it before.

**Comment by pkgw** [comment]
OK, that's reassuring, since it would be hard for me to see how the things that I've been doing would have changed the behavior here.

I think I understand the problem here and should be able to publish a candidate fix as soon as the new deployment system is up and running.

**Comment by pkgw** [comment]
@patudom This should be fixed now. Please reopen or file a new ticket if not.
