### ISSUE TITLE
Saturn's rings, Milky Way, and SDSS galaxies not appearing in Solar System

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-web-client#286]
Some key imagery (Saturn's rings, Milky Way, and Sloan galaxies) are not appearing in Solar System view. I tried two browsers (Chrome & Firefox) and I tried clearing caches

(I am supposed to be doing an online demo for 100+ middle school students in 2 days, so it would be really great if this could be fixed before then.  Thank you!)

**Comment by patudom** [comment]
<img width="1167" alt="Screen Shot 2020-04-01 at 5 58 56 PM" src="https://user-images.githubusercontent.com/12750048/78194454-32b03780-744b-11ea-9cee-9535d3e99af7.png">

**Comment by pkgw** [comment]
There were some issues related to capitalizations of file names with the new CDN being tested. These should all be fixed now, but please reopen if that's incorrect.
