### ISSUE TITLE
Reticle crosshair setting not observed at the start of new sessions

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-web-client#287]
By default, I keep the crosshair turned off in WWT. The web client "remembers" that this is my setting for it, but all new sessions always start with the crosshair turned "on" anyway. If I click on the settings tab, then the crosshair will go away.  (It seems like it's not checking for that setting until I click on the Settings tab. Once I'm there, it remembers it's supposed to be off, and it turns off the crosshair before I have done anything else).

Repro steps:

- In settings, uncheck "reticle/crosshairs"
- Refresh webclient
- Crosshairs still appear
- Click on Settings. Crosshairs box will already be unchecked without the user doing anything, and the crosshairs will disappear after you click on Settings tab.

(This is a long-standing issue)

**Comment by patudom** [comment]
Oh wow, I never even realized the crosshair was also listed in the Layer Manager. It's not listed there in the desktop client, is it?

You are correct. If I uncheck crosshairs in the layer manager, it remembers that setting correctly when I leave the web client and come back.  (It did the first time I tried it).

But why is it an option to toggle the crosshair in both places?  That seems confusing & unnecessary. Should we pick one method and remove the other option?

**Comment by pkgw** [comment]
@patudom Yes, I think we should. If it's convenient for you to check what the desktop client does, can you report it back here?

**Comment by patudom** [comment]
I just checked. In Desktop v.6.0.4.1, "Crosshairs" is not listed in the layer manager, which would explain why I never looked for it there in the web client.

My vote would be to leave the crosshairs checkbox under settings for the web client and remove it from the layer manager. Where the functionality already exists for the web client to behave like the desktop client, I think it would make sense for them to match.

**Comment by pkgw** [comment]
I believe this is now fixed. Please reopen if that's not the case.
