### ISSUE TITLE
iPhone: Safari issues

### ISSUE THREAD

**Issue by willum070** [WorldWideTelescope/wwt-web-client#29]
Safari-  I have Safari as my default web browser on my phone so when I click on a shared link to an object/view it tries to open it in Safari.  Also when I cut the link and paste it in the address bar the same things happens.  What happens is that Safari only shows the 'http://worldwidetelescope.org/webclient/?client=html5' and misses the full URL  -'http://worldwidetelescope.org/webclient/?client=html5#/place=3.5&cf=93&ra=22.49782&dec=-20.82405&fov=0.42068.  This is probably a browser issue  but we should investigate.

**Comment by kfogel** [comment]
What does "tfs bug 92" refer to?  (Can you give a URL to that bug?  I'm not sure what repository it's in.)

In the meantime, removing the "Prio3" label -- as per phone call today with @patudom and @doctorspaceman, we'll use milestones for scheduling priority.  I'm not sure what milestone "Prio3" corresponded to, but if it's none of the currently-available milestones, please just create one and put this issue in it.

**Comment by doctorspaceman** [comment]
TFS was Microsoft's code management system before going open source. I 
don't think there is any record of old bugs if the information was not 
sufficient when moved over.

Cheers,
Doug

**Comment by thewebkid** [comment]
I do not think this is a webclient bug, but a safari bug. There are lots of blogs about "anchor links" breaking in safari. Might be fixed though. I would assume safari has addressed this by now. Can someone verify?

**Comment by doctorspaceman** [comment]
I had a link on my iPhone 6 apple mail and it opened up in Safari fine. I also used Outlook on the iPhone which had chrome as the default browser and that opened up fine as well.  I bet safari fixed this issue.  I just can't repro it on my phone (iOS 9.0.2).  I'm closing this one.
