### ISSUE TITLE
Planet list: Mars out of order

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-web-client#293]
In Planet view, is there a reason Mars is out of solar system order in the planets drop down menu?  If we want that to be the default object you see when you go to Planet view, can that still be the case, but put Mars between Moon & Jupiter in the dropdown menu?  (This is not a major issue, but I could see teachers/students being bothered by this.)

**Comment by pkgw** [comment]
As far as I can tell, the ordering is just to make Mars be the default. #298 will make this default explicit so that we can update the imagery WTML file used by the web engine with the normal ordering. (This file is separate from the one used in the Windows client.)

**Comment by pkgw** [comment]
This should be fixed now if you do a full browser reload. I've update the `builtin-image-sets.wtml` file used by the 6.x-series webclient — the Windows app will be unaffected.
