### ISSUE TITLE
SDSS galaxies check box should be listed in Layer Manager under 3D Solar System

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-web-client#295]
Currently, the available Layer Manager checkboxes under 3D Solar System only go up through Milky Way.  SDSS galaxies should be added (using whatever label we have in the desktop client).  Especially since it can take a few seconds for all the galaxies to load, without the option listed in the layer manager, users might not realize that the galaxies will appear if they wait long enough.

**Comment by pkgw** [comment]
Should be fixed in pull request #298.
