### ISSUE TITLE
Layer Manager "3D Solar System" menu: rename to "3D Universe"

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-web-client#296]
I get that it's too cumbersome to change the name of the "Solar System" view, but in the layer manager, can we at least rename the menu item "3D Solar System" to "3D Universe," or something broader than "Solar System"?  

The general public holds common misconceptions around the scope of what's in a solar system vs. galaxy vs. universe (and will incorrectly use those terms interchangeably).  We should not be contributing to this by having a menu title of incorrect scope.

**Comment by pkgw** [comment]
I agree that this should be changed to make it scientifically accurate. Will be fixed in #298.
