### ISSUE TITLE
"Open Collection" with local file does not work over HTTPS

### ISSUE THREAD

**Issue by pkgw** [WorldWideTelescope/wwt-web-client#297]
Presumably the other local-file workflows have the same problem. I get a popup of "The URL is malformed".

**Comment by astrojonathan** [comment]
I can play a local tour over https:. I will check collections.

**Comment by astrojonathan** [comment]
Collections are broken on https: for me as well.

**Comment by astrojonathan** [comment]
FITS images work...

**Comment by astrojonathan** [comment]
There is no local option for open image... just URL. it seems to work.

**Comment by pkgw** [comment]
This should be fixed by WorldWideTelescope/wwt-webgl-engine@69ef0c8a535fdea7fd62b9c41fff74e52579e603 in WorldWideTelescope/wwt-webgl-engine#26.
