### ISSUE TITLE
Viewport in "Share this View"

### ISSUE THREAD

**Issue by aagoodman** [WorldWideTelescope/wwt-web-client#300]
https://www.thinglink.com/card/1295138622952964097
Try any HST link there, and it works to the right framing, but try searching the same object & sharing the view & framing is not right.

Also would be nice to save layers shown--I don't think that works.

**Comment by pkgw** [comment]
OK, I see what's going on here. Take this share URL for example:

```
http://www.worldwidetelescope.org/webclient/#/place=45.0&ra=11.33750&dec=12.98810&fov=0.15832
```

The issue is that when a `place=` query parameter is present, the client zooms to the view specified by the Place in preference of the `ra` etc. parameters.

**Comment by astrojonathan** [comment]
Yes. the Imageset is the "set" and the place is the "actor" where the camera points at. The imageset may be a large survey that covers half the sky or more, the place might be M51.

**Comment by pkgw** [comment]
Pull request #301 takes a stab at this. It's merged to master so it's available in the testing prefix, e.g.:

```
http://www.worldwidetelescope.org/testing_webclient/#/place=45.0&ra=11.33750&dec=12.98810&fov=0.15832
```

**Comment by pkgw** [comment]
The code change is now in production.
