### ISSUE TITLE
Web client finder scope link to ADS does not send correct (or any?) metadata

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-web-client#329]
Repro steps:

- Bring up Finder Scope for an object in web client
- Click on Information -> "Look up publication on ADS"
- ADS appears to return a blank search query.

<img width="1383" alt="Screen Shot 2020-10-14 at 2 58 52 PM" src="https://user-images.githubusercontent.com/12750048/96033208-ca94d200-0e2d-11eb-890b-a8d12e7a1d85.png">

**Comment by pkgw** [comment]
I've made a change to try to improve the experience here. Try playing around in the testing webclient:

https://www.worldwidetelescope.org/testing_webclient/

Do the searches seem to behave better? Sometimes the only name associated with an item is an unhelpful one, and there isn't anything that we can do about that, but the basic searches should work more reliably.
