### ISSUE TITLE
Polygons visible on 3D solar system imagery

### ISSUE THREAD

**Issue by egcarter** [WorldWideTelescope/wwt-web-client#38]
When looking at the Solar System with 3D view in the web client, all of the object's surfaces are covered with polygons when "Lighting and Shadows" is selected in the Layer Manager.
![3d jupiter polygons](https://cloud.githubusercontent.com/assets/10760281/8042810/8730ca3a-0dd6-11e5-87f9-b4740b87ae2f.PNG)

**Comment by doctorspaceman** [comment]
This is the same as Issue #61
