### ISSUE TITLE
Duplicate README.mds

### ISSUE THREAD

**Issue by cecilia-donnelly** [WorldWideTelescope/wwt-web-client#41]
There appears to be an earlier version of the top-level README.md in the webclient/ directory.  We should keep only the top-level file.  If [webclient/README.md](https://github.com/WorldWideTelescope/wwt-web-client/blob/master/webclient/README.md) has information specific to that directory, it needs to be more clearly differentiated from the top-level readme.

**Comment by thewebkid** [comment]
I agree. Good catch. Will clean this up.
