### ISSUE TITLE
Complete server-specific README and link from or include in top level

### ISSUE THREAD

**Issue by cecilia-donnelly** [WorldWideTelescope/wwt-web-client#42]
The [server-specific README.md](https://github.com/WorldWideTelescope/wwt-web-client/blob/master/Server/README.md) needs to be completed.  Depending on what type of documentation is intended to be included, it may be folded into the top-level INSTALL.md (see #40) or the top-level README.md.  If neither of those, the top-level README.md should include a link to this more specific document (something like "to learn more about the server, see...").

**Comment by thewebkid** [comment]
Actually, I am going to delete the server directory entirely from this repo. The endpoints live in the website repo now. They desperately need documentation, but the code will have to suffice as documentation until we have time to write thoughtful comments... another good issue. Thank you!

**Comment by cecilia-donnelly** [comment]
@thewebkid Ah, I see!  I saw that note about the endpoints in the README but wasn't sure what it implied.  So this issue should really be "Delete server directory" and we should have another one "Document server endpoints."

**Comment by kfogel** [comment]
Just FYI, in commit 979c328394376 I modified Server/README.md, but now I see that it might go away (and that plan makes sense to me).
