### ISSUE TITLE
What is the webclient/Fakes subdirectory?

### ISSUE THREAD

**Issue by cecilia-donnelly** [WorldWideTelescope/wwt-web-client#43]
Is "Fakes" a typical subdirectory name for this kind of project?  More generally, we should think about documenting the subdirectories in [webclient](https://github.com/WorldWideTelescope/wwt-web-client/tree/master/webclient).  I can see what "Bin" might be, for example, but I'm less sure of the difference between "Properties" and "controls."

**Comment by egcarter** [comment]
Fakes Documentation:


https://msdn.microsoft.com/en-us/library/hh708916.aspx









From: Cecilia Donnelly
Sent: ‎Thursday‎, ‎June‎ ‎11‎, ‎2015 ‎8‎:‎22‎ ‎AM
To: WorldWideTelescope/wwt-web-client





Is "Fakes" a typical subdirectory name for this kind of project? More generally, we should think about documenting the subdirectories in webclient. I can see what "Bin" might be, for example, but I'm less sure of the difference between "Properties" and "controls."

**Comment by cecilia-donnelly** [comment]
@egcarter, thanks!  That helps.  Perhaps we should include links to that documentation in DESIGN.md, once that file is created.
