### ISSUE TITLE
Paste tabular data into layer manager

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-web-client#44]
From Alyssa Goodman email on 4/20 after conversation at Northwestern University with various OpenWWT constituents.

Top request for most people present

**Comment by patudom** [comment]
By this, I assume they mean ability to paste data into layer manager?  Doug - were you there?  Can you comment and edit title of this issue accordingly, please?

**Comment by pkgw** [comment]
Ron added this many moons ago.
