### ISSUE TITLE
Gray out not-yet-working features.

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-web-client#47]
Web client features that have not been "wired up" yet should have buttons grayed out or have some indicator that that feature is still a work in progress.  For example, a planet size slider that doesn't actually do anything should not be there; or it should at least have some indication that it is "coming in the future." 

Most incoming new users will go to the Web Client as their first experience with WWT, so they will not recognize that these are all things that work perfectly well in the desktop client, and if they become frustrated by too many non-functional/confusing buttons, they will abandon WWT before they ever get to trying the desktop client.

Please let me know if it would be helpful/better to call out all these different items as individual tickets.

**Comment by doctorspaceman** [comment]
Yes, we want them listed individually, which I see you have started and we will continue.  I'll close this now.
