### ISSUE TITLE
Tour-authoring in web client

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-web-client#50]
From Alyssa Goodman email on 4/20 after conversation at Northwestern University with various OpenWWT constituents.

**Comment by doctorspaceman** [comment]
I have made a draft specification for this (Web-based Tour Authoring Spec.docx): https://drive.google.com/drive/u/0/folders/0B3UI2GmfMrltVkpzMHJaQU1LNlk

**Comment by philrosenfield** [comment]
I'd like to read that, @doctorspaceman however, the link isn't working.

**Comment by doctorspaceman** [comment]
Phil.  I added you to the sharing list.  If others would like access the file I've attached it here. 

[Uploading Web-based Tour Authoring Spec.docx…]()

**Comment by astrojonathan** [comment]
Fixed
