### ISSUE TITLE
Buggy view switches

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-web-client#53]
Clicking on a thumbnail in a different view takes you to last place you were at in this view, rather than to the object in the thumbnail:

I had been viewing Jupiter in the Sky view, then switched to Solar System view.

I did a "Search" for Crab nebula and got a Sky-based thumbnail of Crab.

When I clicked on the thumbnail, it took me to the Sky view, but it took me to Jupiter, where I had been previously.  I had to click on the thumbnail again to actually go to the Crab Nebula.

Also, even though clicking on the thumbnail took me back to the Sky view, "Look at" still says "Solar System."

![screen shot 2015-06-15 at 3 08 11 pm](https://cloud.githubusercontent.com/assets/12750048/8168454/e290f996-1370-11e5-9010-6b9660776702.png)

Now if I want to go back to the Solar System view, I can't re-select "Solar System" from the dropdown.  I have to switch to a different view first (I can select "Sky" instead, even though I'm already there) before I can go to Solar System.

**Comment by patudom** [comment]
(If it makes a difference, I currently have Doug's "hosts hack" turned on, where my computer is pointing to the Azure servers rather than the standard ones.)

**Comment by thewebkid** [comment]
I have staged a fix for this. Please confirm
