### ISSUE TITLE
Constellation Picture overlays don't work

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-web-client#59]

**Comment by patudom** [comment]
Just tried again on a different computer, and the constellation figures, names, and grid overlays seem to be working fine now.  Maybe when I was running tours earlier it left things in a weird state on my other computer?  Will try to verify that next time I'm at that computer.

Editing now to reflect that constellation pictures still don't work.

**Comment by erinjohn** [comment]
Just checked on Safari & Chrome and they appear fine.

**Comment by patudom** [comment]
Looks like this has been fixed.  Thank you!
