### ISSUE TITLE
Imported images sometimes display backwards (right/left flipped)

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-web-client#60]
For example, images plotted via Flickr/astronometry.net

Apparently, Gus Muench and Dustin Lang have discussed this with Jonathan, and they think there is a bug in WWT - something to do with parity=0 or parity=1.

**Comment by pkgw** [comment]
There is better support for this in the various elements of the workflow right now. @patudom please reopen or file a new bug if a new example emerges.
