### ISSUE TITLE
In Solar System view, grid axis labels and constellation names should scale relative to screen, not world.

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-web-client#62]
Else when you zoom away from Solar System, it does this.
![screen shot 2015-06-15 at 7 30 26 pm](https://cloud.githubusercontent.com/assets/12750048/8172983/076f6a12-1395-11e5-8660-27856346bd97.png)

**Comment by astrojonathan** [comment]
Fixed
