### ISSUE TITLE
Buggy Tour Behavior: No imagery on multiple tours

### ISSUE THREAD

**Issue by erinjohn** [WorldWideTelescope/wwt-web-client#63]
This issue is present with both Chrome and Safari.  The audio tracks play (for the beginning of the tour) but the imagery is all missing--- the view remains blank for the tour titled "The Age of Mars" or centered on the Solar system for the tours "Scales of the Universe" and "Our Lonely Sun".

**Comment by astrojonathan** [comment]
Fixed
