### ISSUE TITLE
Web client install problem: bower:install not found 

### ISSUE THREAD

**Issue by Heybus** [WorldWideTelescope/wwt-web-client#64]
Hello, 
I'm trying to install and run the web client.
After npm install and grunt watch, when running
> grunt bower:install

I get

> Warning: Task "bower:install" not found.

Something missing in Gruntfile.js?

**Comment by thewebkid** [comment]
I thought I had updated the readme, but it looks like we migrated to an install.md. I have updated it. You no longer need bower. All our 3rd party libs are referenced via cdn or nuget now. Very sorry for the confusion. You should be fine as is.
