### ISSUE TITLE
Constellation pictures aren't showing

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#65]
This is also an issue for the desktop client: https://github.com/WorldWideTelescope/wwt-windows-client/issues/26

**Comment by astrojonathan** [comment]
Issues was on the server. The image directory had been moved to Azure storage, but the WTML file for constellations still pointing to the server. I restored the images on the server and the feature works again.

**Comment by doctorspaceman** [comment]
Tested that they are showing up now.
