### ISSUE TITLE
Several Overlay checkboxes don't do anything.

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#66]
The following overlay checkboxes don't do anything (always act as though they are checked).
- Overlay
  - Constellation
  - Grid

This is in the layer manager.

**Comment by doctorspaceman** [comment]
I thought we fixed this during the WWT Developer Workshop in November 2015.

**Comment by astrojonathan** [comment]
Fixed. Now displays same layers as desktop client
