### ISSUE TITLE
Milky Way checkbox wired to background sky

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#71]
Clicking "Milky Way (Dr. R. Hurt)" actually toggles the all-sky background.  This behavior is not in the windows client. We should either 
- re-label this (optical background sky) or 
- remove it until we are actually wire up the 3d galaxy

**Comment by astrojonathan** [comment]
It is consistent with the Desktop Client behavior and labeling. The Milky way is now wired to both, same as desktop.
