### ISSUE TITLE
Rendering errors in Solar System mode

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#73]
Rendering errors in Solar System mode. Probably due to software rendering, maybe fixed when WebGL is turned on.

![html5 planet rendering problem](https://cloud.githubusercontent.com/assets/9676722/10297101/4e084942-6b94-11e5-9ab1-7e91f88a0dd1.jpg)

**Comment by kfogel** [comment]
See also issue #61 re WebGL, on which this is dependent.

**Comment by astrojonathan** [comment]
At close range the affine transform approximation user for fake 3d rendering in the HTML5 canvas drawing breaks down. If we sub-divide enough to avoid the issue, the performance gets terrible.
WebGL avoids this. Wen we turn WebGL on this should go away.

**Comment by astrojonathan** [comment]
WebGL works. Fixed
