### ISSUE TITLE
Lighting from displayed time is not correct

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#74]
Lighting not correct for displayed time

**Comment by doctorspaceman** [comment]
We need to fix this or turn off lighting or time selection for the web client.

**Comment by astrojonathan** [comment]
There is a problem with time, lighting is correct for the rotation of the planets, its just not using the correct time, there must be a time zone conversion issue.

**Comment by astrojonathan** [comment]
Fixed
