### ISSUE TITLE
Galactic mode button doesn't do anything in Solar System mode.

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#78]
Galactic mode button doesn't do anything in Solar System mode.  This is the same behavior as the desktop client.  However, the desktop client doesn't show this button be default (it needs to be created as a custom button).  Since the web client shows the button, it should either work in Solar System mode or be grayed out or something.  This will be harder for the desktop client custom button.

**Comment by astrojonathan** [comment]
Its a sky only thing
