### ISSUE TITLE
Solar System view, Can't pull back to Milky Way beyond planet orbits.

### ISSUE THREAD

**Issue by mjbecker0** [WorldWideTelescope/wwt-web-client#79]

**Comment by astrojonathan** [comment]
This is by design for now. The Web Client does not render any data outside the Solar System, so pulling out any more will only show nothing.

**Comment by mjbecker0** [comment]
Thank you.

**Comment by astrojonathan** [comment]
In the WebGL client you can now pull out beyond the solar system and see the Hipparcos Star catalog in 3d, a oriented imaged of the Milky Way, and the SDSS Comsmos feature from the Desktop version.
