### ISSUE TITLE
Solar System View, Add new skins for Pluto and Ceres post NASA visits.

### ISSUE THREAD

**Issue by mjbecker0** [WorldWideTelescope/wwt-web-client#81]

**Comment by doctorspaceman** [comment]
This is the same as issue #33 in wwt-windows-client

**Comment by patudom** [comment]
Doug, your link is pointing to issue #33 in the web client list instead of the Windows client list.  I'm not sure how to fix it.  (GitHub seems to be creating the link automatically and pointing to the wrong place).

**Comment by doctorspaceman** [comment]
In GitHub the HASH/NUMBER makes a link back to an issue of that number in the same repository.  I just change the hash symbol to NUMBER.  There is a repo called WorldWideTelescope/wwt-home that is a better place for these sort of issues. I'll move this over.

**Comment by doctorspaceman** [comment]
This has been moved over as issue number 2 in wwt-home repo.

**Comment by mjbecker0** [comment]
Thank you !

**Comment by kfogel** [comment]
@doctorspaceman @patudom To make a link to an issue in an other repository, just paste the entire URL of the desired issue.  Like this: https://github.com/WorldWideTelescope/wwt-windows-client/issues/33
