### ISSUE TITLE
Manual entry in Time Selector broken

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#82]
There is a gui for manual time entry but it doesn't do anything.

**Comment by thewebkid** [comment]
I just commited/pushed/deployed a fix. 

https://github.com/WorldWideTelescope/wwt-web-client/commit/95a03d1179e6102f284291374353705f3d69f568

Please verify.

**Comment by doctorspaceman** [comment]
I have verified this is fixed.
