### ISSUE TITLE
Buggy galactic mode button in web client

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-web-client#86]
I haven't been able to reproduce this issue, so I'm not sure how helpful this is, but I wanted to log this for completeness.

@doctorspaceman and I were reviewing several issues around the web client.  When I switched to sky mode and checked "Galactic Plane Mode," the galactic plane view did not straighten out as expected.  Instead, the constellation lines plotted changed into random patterns across the screen.

<img width="1079" alt="screen shot 2015-10-07 at 11 04 31 am" src="https://cloud.githubusercontent.com/assets/12750048/10861537/0c5ff60a-7f5a-11e5-899a-acedfdb88a18.png">

When I tried again later (after closing and reopening the same web browser), it was fine.  So I think something about the sequence of views I looked at before going to galactic plane mode put things into an unhappy state, but I don't know exactly what they were.

**Comment by astrojonathan** [comment]
Can't repro. The rendering issue should be Gone in WebGL
