### ISSUE TITLE
Load web-client in HTTPS

### ISSUE THREAD

**Issue by tingyuansen** [WorldWideTelescope/wwt-web-client#89]
Dear Karl and Ron, @kfogel , @thewebkid 

It was really nice meeting you at the workshop! I have a quick question for you. I am eager to try out the web-client and see if I can replace the window-client with the web-client for the kiosk that I built for Harvard. In that kiosk, we made a HTML wrapper and call terminal commands from the wrapper.

One thing that I realized is that Harvard uses https. It fails to load the web-client scripts which are in http. I also tried protocol-sensitive loading, e.g., instead of https://www, I tried //www. But still it does not allow me to load the web-client codes into a Harvard domain.

I am just wondering if you know there is any easy way around this problem?

Thank you so much!

Cheers,
Yuan-Sen

**Comment by kfogel** [comment]
Hey, @tingyuansen!  Could you supply a ton of reproduction data?  Don't worry about swamping us with details -- all details are good in a bug report.  Say exactly what commands you issued, what files you were using, an exact transcript of the result you saw (contrasted with what you expected), etc.

I understand the general problem you're describing.  But to understand exactly why things are not working, we'll need to know precisely what you tried.  The problem could be a firewall issue, or it could be something in the web-client code, or something else... With more details, we'll be able to figure it out pretty quickly I think.

@thewebkid, are you familiar already with this problem?  Is it a known issue?

**Comment by tingyuansen** [comment]
Hey Karl @kfogel ,

Many thanks for your reply. I wrote a simple script in my homepage for the testing purpose.

https://www.cfa.harvard.edu/~yuan-sen.ting/Homepage/HTML/testing.html

It loads the web-client scripts. If you open it, for e.g., with Google Chrome, the console gives the following error:

"Mixed Content: The page at https://www.cfa.... was loaded over HTTPS, but requested an insecure script 'http://www.worldwidetelescope...." . This request has been blocked: the content must be served over HTTPS."

Hope this helps. Please let me know if you have other questions.


Cheers,
Yuan-Sen

**Comment by kfogel** [comment]
Thanks, @tingyuansen.  I understand the problem now, and have filed [issue 19](https://github.com/WorldWideTelescope/wwt-website/issues/19) in the web site's issue tracker so we support https://.

Now, as a temporary workaround, we could try offering the embed script from another server that supports https already.  But I'd like to hear from @thewebkid whether we can just turn on https for the main WWT site server.

By the way, although I got a page timeout error, I didn't actually get the exact "Mixed Content" error you saw.  Can you tell me what version of Chrome you are running?  (I think the upper-right menu, "About Chrome" item should have this information, if your browser looks like mine.)

**Comment by tingyuansen** [comment]
Hi Karl @kfogel and Ron @thewebkid ,

Many thanks. In the case that the WWT main site cannot support https in the near future, it would be great to have the mirror site.

The version of Google Chrome that I am using is : Version 41.0.2272.118 (64-bit).

Thank you so much!


Cheers,
Yuan-Sen

**Comment by thewebkid** [comment]
Yes, this is a pretty important issue and will somewhat involved. For now, can you try to embed the code without the http: like this? 

<div id="wwtControl"></div>
<script src="//worldwidetelescope.org/embedded-webcontrol.js"></script>

This convention allows SSL-agnostic embedding of scripts. I am not sure it will work, but please try it.

**Comment by thewebkid** [comment]
Well my code didn't paste: Here it is again:

&lt;script src="http://worldwidetelescope.org/embedded-webcontrol.js"&gt;&lt;/script$gt;

**Comment by tingyuansen** [comment]
Hi Ron @thewebkid ,

I changed the script at the same page, but it gives the same error :( . Is there any other way around this problem?

Thanks!



Cheers,
Yuan-Sen

**Comment by thewebkid** [comment]
I just verified we need to load this from a secure origin. The problem is on our end. Will let you know when we fix it. Sorry about this.

**Comment by tingyuansen** [comment]
Ah. Thank you so much!

**Comment by DougBurke** [comment]
I know I have mentioned this to @pkgw multiple times, but is there any news on this? We are soon to move to https which will mean that http://cxc.harvard.edu/csc2/wwt.html will stop working.

**Comment by pkgw** [comment]
We've been gathering information and planning, and I think we have a viable path to rolling out support. What timescale does "soon" mean?

**Comment by DougBurke** [comment]
To be honest, I don't know. I'll try to get some clarity on that. Thanks.

(not on the week timescale, so I guess more than a month, but presumably
soon)

**Comment by pkgw** [comment]
Fixed!
