### ISSUE TITLE
Web client tours not working

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-web-client#90]
Is someone in the middle of a fix on the web client tours?  Things seem broken right now.  

The tour thumbnails are missing, 
<img width="690" alt="screen shot 2015-12-02 at 11 15 26 pm" src="https://cloud.githubusercontent.com/assets/12750048/11551805/d841befc-994a-11e5-94f9-079c3c632d22.png">

and when you click "play" the tour doesn't actually run (although all the WWT controls disappear as if it is trying to play the tour, but it just sits on the current view).
<img width="1215" alt="screen shot 2015-12-02 at 11 15 46 pm" src="https://cloud.githubusercontent.com/assets/12750048/11551812/e30a135c-994a-11e5-84ef-c2486dbf4cd1.png">

**Comment by thewebkid** [comment]
We are looking into this. We (Jonathan and I)  spent some hours
troubleshooting and we still do not know the full root cause. However, you
can use http://worldwidetelescope.org/webclient/?debug=1 and it should work
until we have a fix that works for everyone.

Thanks for this catch. We are working hard to fix it as best we can.

Ron

**Comment by astrojonathan** [comment]
This was fixed Dec 3rd or 4th.. Should have been closed then. There was a server issue.

**Comment by kfogel** [comment]
Thanks, @astrojonathan.  I assume that was a production instance issue -- i.e., not a problem that ever showed up in the `wwt-web-site` source tree in git, as none of the commits around that time were related to this.

**Comment by astrojonathan** [comment]
This was a production problem. It appears that files had been accidently moved via a drag-and-drop to another folder on one of the production servers, causing request for them to fail. The load balancer would have more affinity to one or the other and cause intermittent issues, combine that with edge network caching and it was masking all symptoms sometimes and very hard to repro, until it all fell over at once when the edge network cache flushed and the wrong server was being favored. :-)

**Comment by kfogel** [comment]
Ahem.  Let me just say how glad I am that it was you and Ron who had to debug this and not me! :-)

**Comment by doctorspaceman** [comment]
Thanks Jonathan and Ron for figuring this out.  I guess this is a time 
when the caching and distributed networking architecture worked against 
us to hide this problem.  I tried ti tout and it seems to work the same 
in the regular and debug modes.  So are things restored now?

Thanks,
Doug
