### ISSUE TITLE
Clicking "Properties" on image in bottom bar-info window can't close

### ISSUE THREAD

**Issue by aagoodman** [WorldWideTelescope/wwt-web-client#91]
If one clicks the "Properties" button in the Finder Scope after right-clicking on a thumbnail preview image that shows up as  in the bottom bar, as within the current view, then a window opens that's partially off the bottom of the web browser window.  Not only is the information unreadable off the screen, but because one cannot click any choice at this point, there's no way to close the window.  (I was using Safari for this test.)

**Comment by patudom** [comment]
@pkgw 

Bumping this, as it is still an issue.

"Properties" box needs to pop up to a location where the full box is viewable.  (See problem in lower left of this screenshot).

<img width="1269" alt="Screen Shot 2020-04-06 at 5 49 07 PM" src="https://user-images.githubusercontent.com/12750048/78608539-1dfae780-782f-11ea-9e51-60168008e4bb.png">

**Comment by patudom** [comment]
@aagoodman, you can work around the issue by shrinking the browser window a lot, then bring up the Properties box.  When you reexpand the browser window, the whole properties box will then be visible.  (But it should pop up to a sensible location in the first place, so the user doesn't have to mess with the browser sizing to get it to appear.)

**Comment by pkgw** [comment]
I've just deployed to production an attempted fix for this issue (#302). You may need to clear your browser cache to see it take effect. The placement of the Properties box is sometimes a bit awkward but it should be staying within the viewport now.
