### ISSUE TITLE
While loading a FITS image only the main header is checked and not the Primary HDU header

### ISSUE THREAD

**Issue by harcalion** [WorldWideTelescope/wwt-web-client#92]
Some FITS files (like the ones generated by the Herschel mission, see attached file), do not have NAXIS, CROTAi, CDELTi, etc. in the main header, but in the Primary HDU header.

Since WWT only checks the main header of the FITS file (until the END keyword), these FITS files cannot be loaded by the program and they fail with the error message: "The image file did not contain valid AVM metadata to position it in the sky".

The reason is that:
NumAxis becomes 0 because NAXIS is in the primary HDU header (not parsed).
WCS is only computed if NumAxis > 1.
Valid AVM means valid WCS.

[test.zip](https://github.com/WorldWideTelescope/wwt-web-client/files/95704/test.zip)

**Comment by doctorspaceman** [comment]
This is an issue for the desktop client not the webclient.  I have moved this to issue 59 in the wwt-desktop-client repo and am closing this one.
