### ISSUE TITLE
HTML5 Web Client Menu on iPhone - "Search" and "Reset Camera" buttons don't work 

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#93]
When viewing the HTML5 web client on an iPhone (tested with Safari & Chrome for iPhone 6S), the Menu (upper right) bring up a small menu of actions: Explore, Tours, Search, View, Settings, Layers. Under that there is a button to "Reset Camera". 

The _Search_ doesn't and _Reset Camera_ don't appear to do anything.
![20160208_191058000_ios](https://cloud.githubusercontent.com/assets/9676722/12896231/81356400-ce66-11e5-8ee3-ff607d2f069c.png)

**Comment by thewebkid** [comment]
These should work now. Confirmed on my galaxy s9 and chrome iphone emulator. Please reopen if I am wrong
