### ISSUE TITLE
View Menu on Web Client on iPhone shows altitude in "au" should be "meters"

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#94]
On an iPhone (Safari/Chrome iOS 9) in the view menu (which it gets from the phone's GPS) it does detect the lat/long ok and the altitude (I think), but the units on altitude are listed as "au" and it should be "meters" or "m".

![20160208_175838000_ios](https://cloud.githubusercontent.com/assets/9676722/12896436/9e5459be-ce67-11e5-9ba5-09c6ad352bab.png)

**Comment by thewebkid** [comment]
fixed and staged
