### ISSUE TITLE
No SolarSystem Context Menu on HTML5 Web Client for iPhone

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#96]
When you are "Looking at: SolarSystem" in the mobile (responsive design to a small iPhone) there is no context menu shown in the bottom left (as there is or context searched in Sky mode for example).  In the desktop browser there _is_ a proper context menu shown for this.  Only a problem on a small device.

**Comment by thewebkid** [comment]
This one could take a while to fix - currently the desktop context panel only shows planets and moons. Assume you want this and a skyball? Estimate 3 hours

**Comment by thewebkid** [comment]
There is a context menu in mobile solar system mode now.
