### ISSUE TITLE
Open Image in Web Client not working

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-web-client#98]
In the web client when I try to open an AVM-tagged image using Explore/Open/Image and it never loads.  

As a test, I took an AVM-tagged image that opened fine on the desktop client.
  * http://jansky.phys.northwestern.edu/test.jpg
and then tried to open it on the webclient and the UI just sits there with no updates and the image doesn't show up.

This also tried to put a WTML file on a server and open it (which just had this test image)
  * http://jansky.phys.northwestern.edu/TiledImage.wtml
and it also has the same problem.

**Comment by thewebkid** [comment]
I am cleaning up old bugs. This one is fixed but was never closed. I just tried it and it works fine. The wtml file is no longer there, so didn't check that.
